;; Place this file in C:\Users\Username\AppData\Roaming and point to the appropriate files
(setq user-init-file (concat (getenv "EMACSCFG") "\\.emacs.d\\init.el"))
(setq user-emacs-directory (concat (getenv "EMACSCFG") "\\.emacs.d\\"))
;;(setq default-directory (concat (getenv "EMACSCFG") "\\def_dir\\")")
;;(setenv "HOME" (concat (getenv "EMACSCFG") "\\def_dir\\"))
;;(load user-init-file)
;;(setq base-dir-rj "C:/Users/rjain5/Google Drive/emacs_settings")
;;(setq user-init-file (concat base-dir-rj "/.emacs.d/init.el"))
;;(setq user-emacs-directory (concat base-dir-rj "/.emacs.d/"))
;;(setq default-directory (concat base-dir-rj "/def_dir/")")
;;(setenv "HOME" (concat base-dir-rj "/def_dir/"))
(load user-init-file)
